defaults:
- _self_
- mlflow: default
- trainer: default
- model: basic_nn
- data: default

random_state: 38
checkpoint_path: /Users/ruanwko/Desktop/mlops_project/1/af1d7ea891304f74bb0ab7a7f9b820ae/checkpoints/epoch=3-step=6276.ckpt